FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        whois \
        nmap \
        curl \
        dnsutils \
        iputils-ping \
        build-essential \
        gcc \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "advanced_recon.py"]
