FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y nmap whatweb wafw00f
RUN pip install whois
RUN pip install theharvester
ENTRYPOINT ["python", "advanced_recon.py"]
